# Generated by Django 6.0.4 on 2026-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_frames', models.IntegerField(default=0)),
                ('source_file', models.CharField(blank=True, help_text='Original JSON filename', max_length=255)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RadarFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('num_detected_points', models.IntegerField(default=0)),
                ('num_detected_tracks', models.IntegerField(default=0)),
                ('point_cloud', models.JSONField(default=list)),
                ('track_data', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['frame_number'],
            },
        ),
    ]
