# Generated by Django 6.0.4 on 2026-04-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
        ('sensors_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionsession',
            name='radar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sensors_devices.radar'),
        ),
        migrations.AddField(
            model_name='radarframe',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='developer.acquisitionsession'),
        ),
    ]
