# Generated by Django 6.0.4 on 2026-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the room (e.g., Living Room, Kitchen)', max_length=100)),
                ('width', models.FloatField(help_text='Width in meters (X axis)')),
                ('depth', models.FloatField(help_text='Depth in meters (Y axis)')),
                ('height', models.FloatField(default=3.0, help_text='Height in meters (Z axis)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
