# Generated by Django 6.0.4 on 2026-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
