# Generated by Django 6.0.4 on 2026-04-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Radar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_id', models.CharField(max_length=100, unique=True)),
                ('is_master', models.BooleanField(default=False, help_text='Indicates if this radar is the master in its room')),
                ('status', models.CharField(choices=[('UNASSIGNED', 'Not Assigned to Room'), ('PENDING', 'Calibration Pending'), ('ACTIVE', 'Active and Monitoring'), ('ERROR', 'Error State')], default='UNASSIGNED', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radars', to='environments.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
