# Generated by Django 6.0.4 on 2026-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Indicates if the radar is currently online and communicating'),
        ),
    ]
