# Generated by Django 6.0.4 on 2026-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_devices', '0002_radar_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='radar',
            name='azimuth_deg',
            field=models.FloatField(default=0.0, help_text='Rotação no plano XY (graus)'),
        ),
        migrations.AddField(
            model_name='radar',
            name='is_calibrated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radar',
            name='pos_x',
            field=models.FloatField(default=0.0, help_text='Posição X na sala (metros)'),
        ),
        migrations.AddField(
            model_name='radar',
            name='pos_y',
            field=models.FloatField(default=0.0, help_text='Posição Y na sala (metros)'),
        ),
        migrations.AddField(
            model_name='radar',
            name='pos_z',
            field=models.FloatField(default=0.0, help_text='Altura Z do radar (metros)'),
        ),
        migrations.AddField(
            model_name='radar',
            name='tilt_deg',
            field=models.FloatField(default=0.0, help_text='Inclinação em relação ao chão (graus)'),
        ),
    ]
