# Generated by Django 6.0.4 on 2026-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors_devices', '0003_radar_azimuth_deg_radar_is_calibrated_radar_pos_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radar',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Not Assigned to Room'), ('PENDING', 'Calibration Pending'), ('ACTIVE', 'Active and Monitoring'), ('ERROR', 'Error State'), ('SYNCING', 'Synchronizing Data')], default='UNASSIGNED', max_length=20),
        ),
    ]
