# Generated by Django 6.0.4 on 2026-04-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('distance_covered', models.FloatField(default=0.0)),
                ('average_speed', models.FloatField(default=0.0)),
                ('activity_level', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
