# Generated by Django 6.0.4 on 2026-04-24 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('environments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysummary',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='environments.room'),
        ),
        migrations.AlterUniqueTogether(
            name='activitysummary',
            unique_together={('room', 'date')},
        ),
    ]
